[package]
name = "chipster"
version = "0.1.0"
authors = ["Sergey Pepyakin <s.pepyakin@gmail.com>"]

[dependencies]
chip8 = { path = "../chip8" }
sdl2 = "0.30.0"
error-chain = "0.10.0"
clap = "2.5.1"
rand = "0.3"
void = "1"
