dist: trusty
addons:
  apt:
    packages:
      - libsdl2-dev
before_install:
  - sudo apt-get -qq update

language: rust
rust:
  - nightly
notifications:
  email:
    - s.pepyakin@gmail.com
before_script:
  - rustc --version
  - cargo --version
script:
  - ./test_all.sh
