[package]
name = "chip8"
version = "0.1.0"
authors = ["Sergey Pepyakin <s.pepyakin@gmail.com>"]

[dependencies]
rand = "0.3"
portaudio = "0.6.4"
piston_window = "0.47.0" 
clap = "2.5.1"
byteorder = "0.5"
