[package]
name = "chip8"
version = "0.1.0"
authors = ["Sergey Pepyakin <s.pepyakin@gmail.com>"]

[lib]

[features]
default = ["std"]
std = []

[dependencies]
rand = "0.3"
byteorder = "0.5"
enum_primitive = "*"
error-chain = "0.10.0"
